In [19]:
import pandas as pd
data=pd.read_csv(r'C:\Users\HP\Desktop\int\kidney\kidney_disease.csv')
data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [13]:
data.shape

(400, 26)

In [14]:
data.describe()

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
count,400.000000,391.000000,388.000000,353.000000,354.000000,351.000000,356.000000,381.000000,383.000000,313.000000,312.000000,348.000000
mean,199.500000,51.483376,76.469072,1.017408,1.016949,0.450142,148.036517,57.425722,3.072454,137.528754,4.627244,12.526437
std,115.614301,17.169714,13.683637,0.005717,1.352679,1.099191,79.281714,50.503006,5.741126,10.408752,3.193904,2.912587
min,0.000000,2.000000,50.000000,1.005000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,3.100000
25%,99.750000,42.000000,70.000000,1.010000,0.000000,0.000000,99.000000,27.000000,0.900000,135.000000,3.800000,10.300000
50%,199.500000,55.000000,80.000000,1.020000,0.000000,0.000000,121.000000,42.000000,1.300000,138.000000,4.400000,12.650000
75%,299.250000,64.500000,80.000000,1.020000,2.000000,0.000000,163.000000,66.000000,2.800000,142.000000,4.900000,15.000000
max,399.000000,90.000000,180.000000,1.025000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,17.800000

In [15]:
data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd

In [16]:
pd.set_option("display.max_columns",None)

In [17]:
data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [28]:
data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,2,normal,0,0,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,1,4,1,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,2,normal,0,0,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,0,3,1,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,1,normal,0,0,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,0,4,1,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,abnormal,1,0,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,1,3,1,1,1,1,0
4,4,51.0,80.0,1.010,2.0,0.0,1,normal,0,0,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,0,3,1,0,0,0,0

In [46]:
data['rc'].value_counts()

rc
5.2    18
4.5    16
4.9    14
4.7    11
4.8    10
3.9    10
4.6     9
3.4     9
5.9     8
5.5     8
6.1     8
5.0     8
3.7     8
5.3     7
5.8     7
5.4     7
3.8     7
5.6     6
4.3     6
4.2     6
3.2     5
4.4     5
5.7     5
6.4     5
5.1     5
6.2     5
6.5     5
4.1     5
3.6     4
6.3     4
6.0     4
4.0     3
3.3     3
4       3
3.5     3
2.9     2
3.1     2
2.6     2
2.1     2
2.5     2
2.8     2
3.0     2
2.7     2
5       2
2.3     1
\t?     1
2.4     1
3       1
8.0     1
Name: count, dtype: int64

In [113]:
data.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [91]:
data['pcv']=data['pcv'].fillna(35)
data['wc']=data['wc'].fillna(7200)

In [47]:
data['rc']=data['rc'].replace({'\t?':4.8})

In [88]:
data['pcv']=data['pcv'].replace({'\t?':35})

In [89]:
data['wc']=data['wc'].replace({'\t?':7500})

In [52]:
data['rc'].value_counts()

rc
5.2    18
4.5    16
4.9    14
4.7    11
4.8    10
3.9    10
4.6     9
3.4     9
5.9     8
5.5     8
6.1     8
5.0     8
3.7     8
5.3     7
5.8     7
5.4     7
3.8     7
5.6     6
4.3     6
4.2     6
3.2     5
4.4     5
5.7     5
6.4     5
5.1     5
6.2     5
6.5     5
4.1     5
3.6     4
6.3     4
6.0     4
4.0     3
3.3     3
4       3
3.5     3
2.9     2
3.1     2
2.6     2
2.1     2
2.5     2
2.8     2
3.0     2
2.7     2
5       2
2.3     1
4.8     1
2.4     1
3       1
8.0     1
Name: count, dtype: int64

In [55]:
data.drop(columns=['rc'], inplace=True)
data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,2,1,0,0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,1,4,1,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,2,1,0,0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,0,3,1,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,1,1,0,0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,0,4,1,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,1,3,1,1,1,1,0
4,4,51.0,80.0,1.010,2.0,0.0,1,1,0,0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,1,1,0,0,140.000000,49.0,0.5,150.000000,4.900000,15.7,47,6700,0,3,1,0,0,0,2
396,396,42.0,70.0,1.025,0.0,0.0,1,1,0,0,75.000000,31.0,1.2,141.000000,3.500000,16.5,54,7800,0,3,1,0,0,0,2
397,397,12.0,80.0,1.020,0.0,0.0,1,1,0,0,100.000000,26.0,0.6,137.000000,4.400000,15.8,49,6600,0,3,1,0,0,0,2
398,398,17.0,60.0,1.025,0.0,0.0,1,1,0,0,114.000000,50.0,1.0,135.000000,4.900000,14.2,51,7200,0,3,1,0,0,0,2
399,399,58.0,80.0,1.025,0.0,0.0,1,1,0,0,131.000000,18.0,1.1,141.000000,3.500000,15.8,53,6800,0,3,1,0,0,0,2

In [92]:
data.drop(columns=['id'], inplace=True)
data.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,2,0,0,0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,1,4,1,0,0,0,0
1,7.0,50.0,1.020,4.0,0.0,2,0,0,0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,0,3,1,0,0,0,0
2,62.0,80.0,1.010,2.0,3.0,1,0,0,0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,0,4,1,1,0,1,0
3,48.0,70.0,1.005,4.0,0.0,1,1,1,0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,1,3,1,1,1,1,0
4,51.0,80.0,1.010,2.0,0.0,1,0,0,0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,0,3,1,0,0,0,0

In [94]:
#for str data
data['rbc']=data['rbc'].fillna(method='ffill')
data['pc']=data['pc'].fillna(method='ffill')
data['pcc']=data['pcc'].fillna(method='ffill')
data['ba']=data['ba'].fillna(method='ffill')
data['htn']=data['htn'].fillna(method='ffill')
data['dm']=data['dm'].fillna(method='ffill')
data['cad']=data['cad'].fillna(method='ffill')
data['appet']=data['appet'].fillna(method='ffill')
data['pe']=data['pe'].fillna(method='ffill')
data['ane']=data['ane'].fillna(method='ffill')
data['classification']=data['classification'].fillna(method='ffill')

C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['rbc']=data['rbc'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['pc']=data['pc'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['pcc']=data['pcc'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['ba']=data['ba'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['htn']=data['htn'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['dm']=data['dm'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['cad']=data['cad'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['appet']=data['appet'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['pe']=data['pe'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['ane']=data['ane'].fillna(method='ffill')
C:\Users\HP\AppData\Local\Temp\ipykernel_5208\3085800816.py:12: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['classification']=data['classification'].fillna(method='ffill')

In [97]:
#for numerical datadata
data['age']=data['age'].fillna(data['age'].median())
data['bp']=data['bp'].fillna(data['bp'].median())
data['sg']=data['sg'].fillna(data['sg'].median())
data['al']=data['al'].fillna(data['al'].median())
data['su']=data['su'].fillna(data['su'].median())
data['bgr']=data['bgr'].fillna(data['bgr'].median())
data['bu']=data['bu'].fillna(data['bu'].median())
data['sc']=data['sc'].fillna(data['sc'].median())
data['sod']=data['sod'].fillna(data['sod'].median())
data['pot']=data['pot'].fillna(data['pot'].median())
data['hemo']=data['hemo'].fillna(data['hemo'].median())
data['pcv']=data['pcv'].fillna(data['pcv'].median())

In [99]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data['rbc']=l.fit_transform(data['rbc'])
data['pc']=l.fit_transform(data['pc'])
data['pcc']=l.fit_transform(data['pcc'])
data['ba']=l.fit_transform(data['ba'])
data['htn']=l.fit_transform(data['htn'])
data['dm']=l.fit_transform(data['dm'])
data['cad']=l.fit_transform(data['cad'])
data['appet']=l.fit_transform(data['appet'])
data['pe']=l.fit_transform(data['pe'])
data['ane']=l.fit_transform(data['ane'])
data['classification']=l.fit_transform(data['classification'])
data.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,2,0,0,0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,1,4,1,0,0,0,0
1,7.0,50.0,1.020,4.0,0.0,2,0,0,0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,0,3,1,0,0,0,0
2,62.0,80.0,1.010,2.0,3.0,1,0,0,0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,0,4,1,1,0,1,0
3,48.0,70.0,1.005,4.0,0.0,1,1,1,0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,1,3,1,1,1,1,0
4,51.0,80.0,1.010,2.0,0.0,1,0,0,0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,0,3,1,0,0,0,0

In [100]:
x=data.drop(['classification'],axis=1)
y=data['classification']

In [102]:
x

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,1.020,1.0,0.0,2,0,0,0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,1,4,1,0,0,0
1,7.0,50.0,1.020,4.0,0.0,2,0,0,0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,0,3,1,0,0,0
2,62.0,80.0,1.010,2.0,3.0,1,0,0,0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,0,4,1,1,0,1
3,48.0,70.0,1.005,4.0,0.0,1,1,1,0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,1,3,1,1,1,1
4,51.0,80.0,1.010,2.0,0.0,1,0,0,0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,0,3,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,1,0,0,0,140.000000,49.0,0.5,150.000000,4.900000,15.7,47,6700,0,3,1,0,0,0
396,42.0,70.0,1.025,0.0,0.0,1,0,0,0,75.000000,31.0,1.2,141.000000,3.500000,16.5,54,7800,0,3,1,0,0,0
397,12.0,80.0,1.020,0.0,0.0,1,0,0,0,100.000000,26.0,0.6,137.000000,4.400000,15.8,49,6600,0,3,1,0,0,0
398,17.0,60.0,1.025,0.0,0.0,1,0,0,0,114.000000,50.0,1.0,135.000000,4.900000,14.2,51,7200,0,3,1,0,0,0
399,58.0,80.0,1.025,0.0,0.0,1,0,0,0,131.000000,18.0,1.1,141.000000,3.500000,15.8,53,6800,0,3,1,0,0,0

In [103]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    2
396    2
397    2
398    2
399    2
Name: classification, Length: 400, dtype: int64

In [104]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [105]:
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((320, 23), (80, 23), (320,), (80,))

In [106]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(xtrain,ytrain)

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [107]:
model.predict(xtest)

array([0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0,
       0, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0,
       0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0], dtype=int64)

In [108]:
model.score(xtest,ytest)

0.875

In [109]:
data.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,2,0,0,0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,1,4,1,0,0,0,0
1,7.0,50.0,1.020,4.0,0.0,2,0,0,0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,0,3,1,0,0,0,0
2,62.0,80.0,1.010,2.0,3.0,1,0,0,0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,0,4,1,1,0,1,0
3,48.0,70.0,1.005,4.0,0.0,1,1,1,0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,1,3,1,1,1,1,0
4,51.0,80.0,1.010,2.0,0.0,1,0,0,0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,0,3,1,0,0,0,0

In [112]:
model.predict([[48,89,1.000,3.0,2,0,1,0,0,115.000000,30.0,111.000000,4.633420,11.6,32,7300,1,3,1,0,1,0,0]])

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([2], dtype=int64)